# ============================================
# Profile DEV - Local Development Environment
# ============================================

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ompay_db
    username: ompay_user
    password: M@hmk!10
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: K9mP2xL7nQ4vR8wT3yU6zF5bN1cD4gH0
    expiration: 86400000
    refresh-expiration: 604800000

logging:
  level:
    com.orangemoney.api: DEBUG